-- [IV] DDL, DCL, DML
/* SQL
(1) - DCL: 
    사용자 계정 생성 CREATE USER, 권한부여 GRANT
    권한 박탈       REVOKE,     사용자 계정 삭제 DROP USER
    트렌젝션 명령어(ROLLBACK, COMMIT)

(2) DDL:
   테이블생성 CREATE TABLE, 테이블 구조변경 ALTER TABLE, 테이블삭제 DROP TABLE
   
(3) DML: CRUD 
  입력 INSERT, 검색 SELECT, 수정 UPDATE, 삭제 DELETE -DML은 취소 가능
*/

--      ★DDL★
--  1. 테이블 생성(CREATE TABLE 테이블 명): 테이블의 구조를 정의
    -- ORACLE 타입: NUMBER(38이하의 자릿수), DATE, VARCHAR2(4OO0이하의 바이트수), CLOB
CREATE TABLE BOOK(
    BOOKID NUMBER(4), -- BOOKID필드의 타입은 숫자4자리
    BOOKNAME VARCHAR2(20), --BOOKNAME필드의 타입은 문자 20바이트 (한글1자=3바이트)
    PUBLISHER VARCHAR(20),
    RDATE   DATE,     -- RDATE필드의 타입은 DATE형(날짜+시간)
    PRICE NUMBER(8,2), -- PRICE필드의 타입은 숫자 전체8자리 중 소숫점 2자리
    PRIMARY KEY(BOOKID) -- 제약조건: BOOKID를 주키 (PRIMARY KEY) 필드로
);
SELECT * FROM BOOK;
DESC BOOK;
DROP TABLE BOOK; -- 테이블 삭제(DROP TABLE테이블명)

CREATE TABLE BOOK(
    BOOKID NUMBER(4)PRIMARY KEY, -- BOOKID필드의 타입은 숫자4자리
    BOOKNAME VARCHAR2(20), --BOOKNAME필드의 타입은 문자 20바이트 (한글1자=3바이트)
    PUBLISHER VARCHAR(20),
    RDATE   DATE,     -- RDATE필드의 타입은 DATE형(날짜+시간)
    PRICE NUMBER(8,2) -- PRICE필드의 타입은 숫자 전체8자리 중 소숫점 2자리
);

SELECT * FROM EMP;
SELECT * FROM DEPT;
INSERT INTO EMP VALUES (7369, '홍길동', NULL, NULL, NULL,NULL,NULL, 40);

-- DEPT와 유사한 DEPT01 생성: DEPTNO(숫2-PK), DNAME(문14), LOC(문13)
CREATE TABLE DEPT01(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR(14),
    LOC   VARCHAR(13)
);
INSERT INTO DEPT01 VALUES(10, '전산실', '신림');
SELECT * FROM DEPT01;
ROLLBACK;
-- EMP와 유사한 EMP01 생성: EMPNO(숫4-PK), ENAME(문10), HIREDATE(날), SAL(숫 7.2), DEPTNO(숫2,FK)

CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    HIREDATE  DATE,
    SAL NUMBER(7,2),
    DEPTNO NUMBER(2) REFERENCES DEPT01(DEPTNO)
);

CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    HIREDATE  DATE,
    SAL NUMBER(7,2),  -- 소수점 앞 5자리 소수점 뒤 2자리. 총 7자리
    DEPTNO NUMBER(2),
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(EMPTNO) REFERENCES DEPT01(DEPTNO)
);
INSERT INTO EMP01 VALUES (1001, '홍길동', SYSDATE, 9999,10);
COMMIT;

SELECT * FROM EMP01;

----- DML -------

-- 1 INSERT INTO 테이블 명 (필드명1, 필드명2, ...) VALUES (값1, 값2, ..);
    -- INSERT INTO 테이블 명 VALUES (값1, 값2, ... 값N);
SELECT * FROM DEPT01;

INSERT INTO DEPT01 VALUES(50, 'ACCOUNTING','SEOUL');
INSERT INTO DEPT01 (DEPTNO, LOC, DNAME) VALUES (60,'신림','개발'); 
INSERT INTO DEPT01 (DEPTNO, LOC, DNAME) VALUES (70,NULL,'영업');
INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES (80, '연구');
SELECT * FROM DEPT01;

-- 서브 쿼리를 이용한 INSERT
    -- EX. DEPT테이블의 20~40부서의 내용을 DEPT01테이블에 INSERT 
    INSERT INTO DEPT01 SELECT * FROM DEPT WHERE DEPTNO >10;
    SELECT * FROM DEPT01;
    
-- PDF 1PAGE 연습문제
DROP TABLE SAM01;
CREATE TABLE SAM01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER(7,2)
);
SELECT * FROM SAM01;
SELECT * FROM EMP;
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE DEPTNO =10;
INSERT INTO SAM01 VALUES(1000, 'APPLE', 'POLICE',10000);
INSERT INTO SAM01 VALUES(1010, 'BANANA', 'NORSE',15000);
INSERT INTO SAM01 VALUES(1020, 'ORANGE', 'DOCTOR',25000);
INSERT INTO SAM01 VALUES(1030, 'VERY', NULL,25000);
INSERT INTO SAM01 VALUES(1040, 'CAT', NULL,2000);
COMMIT;
SELECT * FROM SAM01;

-- 2. UPDATE 테이블 명 SET 필드명1 [, 필드값2= 값2, ...필드명N= 값N] [WHERE 조건];
DROP TABLE EMP01;
-- 서브쿼리를 이용한 테이블 생성
CREATE TABLE EMP01 AS SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP;
SELECT * FROM EMP01;
    -- EX. 부서번호를 30번으로 수정
    UPDATE EMP01 SET DEPTNO=30;
    
    -- EX 모든 사원(EMP01)의 급여 (SAL)를 10%인상
    UPDATE EMP01 SET SAL = SAL*1.1;
    ROLLBACK;
   
    --EX. EMP01테이블의 10번부서의 직원을 30번 부서로
    UPDATE EMP01 SET DEPTNO= 30 WHERE DEPTNO=10;
    ROLLBACK;
    
    -- EX. SCOTTD의 부서번호를 10으로, JOB은 'MANAGER'로 SAL과 COMM은 500$씩 인상,
        -- 입사일은 오늘로, 상사는 'KING'으로 수정
    UPDATE EMP01 SET DEPTNO=10,
                    JOB= 'MAMGER',
                    SAL= SAL+500,
                    COMM = NVL(COMM,0) + 500,
                    -- HIREDATE= TO_DATA('25/11/17', 'RR/MM/DD'),
                    HIREDATE= SYSDATE, --SYSDATE:지금
                    MGR = (SELECT EMPNO FROM EMP01 WHERE ENAME='KING')
        WHERE ENAME='SCOTT';
SELECT * FROM EMP;
    -- EX. 모든 사원의 급여와 입사일을 'KING'의 급여와 입사일로 수정
SELECT * FROM EMP;

    UPDATE EMP
        SET SAL = (SELECT SAL FROM EMP WHERE ENAME= 'KING'),
        HIREDATE = (SELECT HIREDATE FROM EMP WHERE ENAME='KING');
    
    ROLLBACK;
    
-- 3. DELETE FROM 테이블 명 [WHERE = 조건]
SELECT * FROM EMP01;
DELETE FROM DEPT; -- 불가(EMP테이블의 참조된 데이터가 있어서)
ROLLBACK;
SELECT * FROM EMP;
    -- EX.EMP01에서 'FORD' 직원 퇴사
    DELETE FROM EMP01 WHERE ENAME='FORD';
    -- EX. EMP01에서 30번 부서 직원을 삭제
    DELETE FROM EMP01 WHERE DEPTNO =30;
    -- EX. 부서명이 RESEARCH 부서인 직원을 삭제
    DELETE FROM EMP01
    WHERE DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME='RESEARCH');
    
    -- EX. SAM01테이블에서 JOB이 정해지지않은 사원 삭제
    DELETE FROM SAM01 WHERE JOB IS NULL;
    -- EX. SAM01테이블에서 이름이 ORANGE인 데이터 삭제
    DELETE FROM SAM01 WHERE ENAME='ORANGE';
    SELECT * FROM SAM01;






DROP TABLE MY_DATA;
CREATE TABLE MY_DATA(
   ID NUMBER(4) PRIMARY KEY,
   NAME VARCHAR2(10),
   USERID VARCHAR2(30),
   SALARY NUMBER(10,2)
);
INSERT INTO MY_DATA values( 1, 'Scott','sscott',10000);
INSERT INTO MY_DATA values( 2, 'Ford','fford',13000);
INSERT INTO MY_DATA values( 3, 'Patel','ppatel',33000);
INSERT INTO MY_DATA values( 4, 'Report','rreport',23500);
INSERT INTO MY_DATA values( 5, 'Good','ggood',44450);
SELECT * FROM MY_DATA;
select TO_CHAR(SALARY,'999,999,999.00') AS NEW_SAL from my_data;
COMMIT;

SELECT * FROM MY_DATA;


UPDATE MY_DATA SET SALARY = 65000 WHERE ID = 3;
DELETE FROM MY_DATA WHERE NAME = 'Ford';
COMMIT;
update MY_DATA SET SALARY  = 15000 WHERE SALARY<=15000;
select ID, NAME, USERID, TO_CHAR(SALARY,'999,999,999.00') AS NEW_SAL from my_data;
DROP TABLE MY_DATA;

DROP TABLE EMP01;

CREATE TABLE EMP01 AS SELECT * FROM EMP;
--1 
UPDATE EMP01 SET DEPTNO = 30;
--2 
UPDATE EMP01 SET SAL = SAL *1.1;
--3
UPDATE EMP01 SET SAL = SAL *1.1 WHERE SAL>=3000;
--4
UPDATE EMP01
SET SAL = SAL + 1000
WHERE DEPTNO = (
    SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS'
);
SELECT * FROM DEPT WHERE LOC='DALLAS';
SELECT * FROM EMP01;
ROLLBACK;
--5
UPDATE EMP01 SET DEPTNO =30, JOB ='MANAGER' WHERE ENAME='SCOTT';
--6 
DELETE FROM EMP01 WHERE JOB= 'SALESMAN';
--7
DELETE FROM EMP01 WHERE ENAME = 'FORD';
--8
DELETE FROM SAM01 WHERE JOB IS NULL;
--9
DELETE FROM SAM01 WHERE ENAME= 'ORANGE';
--10
UPDATE EMP01 SET SAL = 1500 WHERE SAL <=1500;
--11
UPDATE EMP01 SET SAL = SAL *0.1 WHERE JOB ='MANAGER';
ROLLBACK;
SELECT * FROM EMP01;


-- 제약조건
-- (1) PRIMARY KEY: 테이블의 각 행을 유일한 값으로 식별하기 위한 필드
-- (2) FOREIGN KEY: 테이블의 열이 다른 테이블의 열을 참조
-- (3) NOT NULL: NULL을 포함하지 않는다
-- (4) UNIQUE: 모든행의 값이 유일해야. NULL값은 허용(NULL은 여러개 가능)
-- (5) CHECK(조건) : 해당 조건이 만족(NULL값 허용)
-- DEFAULT 기본값: 기본 값 설정(해당 열의 데이터를 입력하지 않고
            -- INSERT 하면 NULL이 들어갈 것을 DEFAULT값이 들어가도록)
            
-- DEPT1 & EMP1 테이블 생성
CREATE TABLE DEPT1(
    DEPTNO NUMBER(4),
    DNAME VARCHAR(14) NOT NULL ,
    LOC VARCHAR(13)NOT NULL,
     PRIMARY KEY(DEPTNO),
     UNIQUE(DNAME)
);
CREATE TABLE EMP1(
    EMPNO NUMBER(4),
    ENAME VARCHAR(20) NOT NULL,
    JOB VARCHAR2(20) NOT NULL,
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2),
    PRIMARY KEY(EMPNO),
    CHECK(SAL>0),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT1(DEPTNO)
);
INSERT INTO DEPT1 SELECT * FROM DEPT;
INSERT INTO DEPT1 VALUES (50, 'SALES', '서울'); -- UNIQUE에러
INSERT INTO DEPT1 (DEPTNO, DNAME) VALUES (50, '전산'); -- NOT NULL에러I
INSERT INTO EMP1 (EMPNO, ENAME, JOB, DEPTNO) VALUES (9001, 'HONG', 'MANAGER', 40);
-- INSERT 에서 언급되지 않은 필드는 DEFAULT값 NULL값으로 입력.
SELECT * FROM EMP1 WHERE EMPNO=9001;
INSERT INTO EMP1(EMPNO, ENAME, JOB, SAL) VALUES (9002, 'KIM','MANAGER', 90);


CREATE TABLE MAJOR(
    mCODE NUMBER(4) PRIMARY KEY ,
    mNAME VARCHAR2(20) UNIQUE,
    mOFFICE VARCHAR2(20)
);
CREATE TABLE STUDENT(
    sNO NUMBER(8) PRIMARY KEY,
    sNAME VARCHAR2(20),
    sSCORE NUMBER(5,2) CHECK(sSCORE BETWEEN 0 AND 100),
    mCODE NUMBER(4) REFERENCES MAJOR(mCODE)
);


DROP TABLE STUDENT;
DROP TABLE MAJOR;
INSERT INTO MAJOR VALUES (1, '컴퓨터공학', 'A101호');
INSERT INTO MAJOR VALUES (2, '빅데이터', 'A102호' );

INSERT INTO STUDENT VALUES (101, '홍길동', 99, 1);
INSERT INTO STUDENT VALUES (102, '신길동', 100, 2);
SELECT *FROM STUDENT S, MAJOR M WHERE S.mCODE = M.mCODE;




